### PR TITLE
Commenting

### PR DESCRIPTION
**Pull request by bill-luu**
This branch was made to better understand how Domovoi works for those who are unfamiliar to Python.

Enoch can you look at this to see if there is anything missing or wrong?
Should we actually merge it to master?

---

This change is [Reviewable](https://reviewable.io/reviews/ucsolarcarteam/epsilon-domovoi/15)

### CODE REVIEW

**Comment by ExtraGravity** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[a discussion](https://reviewable.io:443/reviews/ucsolarcarteam/epsilon-domovoi/15#-KT_hUESLKBVi4o5RRJM:-KT_hUESLKBVi4o5RRJN:bmjyapp) (no related file):_
Comments for functions in python should be using docstrings in the style 

``` python
'''
This is known as a docstring in python
'''
def something():
    return 0
```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/epsilon-domovoi/15)_

**Comment by bill-luu** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[a discussion](https://reviewable.io:443/reviews/ucsolarcarteam/epsilon-domovoi/15#-KT_hUESLKBVi4o5RRJM:-KTg3-kE3jAAg_KO26uF:brpeadz) (no related file):_
<details><summary>

<i>Previously, enochtsang (Enoch Tsang) wrote…</i></summary>



> Comments for functions in python should be using docstrings in the style 
> 
> ``` python
> '''
> This is known as a docstring in python
> '''
> def something():
>     return 0
> ```
> 
> </details>
> When is it appropriate to use hashes for comments?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/epsilon-domovoi/15)_

**Comment by ExtraGravity** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[a discussion](https://reviewable.io:443/reviews/ucsolarcarteam/epsilon-domovoi/15#-KT_hUESLKBVi4o5RRJM:-KTgT-Dok_ZK3nDaFkP1:bdgo8yq) (no related file):_
<details><summary>

<i>Previously, bill-luu wrote…</i></summary>



> When is it appropriate to use hashes for comments?
> </details>
> For something where you're explaining just one line of code. Docstrings are often parsed for documentation generators and such, so for classes and functions. If you just need to explain something odd you did in one line, a hash is good.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/epsilon-domovoi/15)_

**Comment by bill-luu** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[a discussion](https://reviewable.io:443/reviews/ucsolarcarteam/epsilon-domovoi/15#-KT_hUESLKBVi4o5RRJM:-KTkjZtlWrU9q661M92i:b-8l3hur) (no related file):_
<details><summary>

<i>Previously, enochtsang (Enoch Tsang) wrote…</i></summary>



> For something where you're explaining just one line of code. Docstrings are often parsed for documentation generators and such, so for classes and functions. If you just need to explain something odd you did in one line, a hash is good.
> </details>
> Is there a reason sublime is highlighting my docstrings differently?
> 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/epsilon-domovoi/15)_

**Comment by ExtraGravity** [comment]
Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

_[a discussion](https://reviewable.io:443/reviews/ucsolarcarteam/epsilon-domovoi/15#-KT_hUESLKBVi4o5RRJM:-KUEqkSOCjmEZs8hF3Ex:bmk4zqw) (no related file):_
<details><summary>

<i>Previously, bill-luu wrote…</i></summary>



> Is there a reason sublime is highlighting my docstrings differently?
> 
> 
> </details>
> Not entirelyi sure, they're still comments. For more information, you can see PEP8's style guide on docstrings.
> https://www.python.org/dev/peps/pep-0008/#documentation-strings

---

_[domovoi.py, line 19 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/epsilon-domovoi/15#-KUErLSdhqPtrl-z4soa:-KUErLSdhqPtrl-z4sob:b6bcy41) ([raw file](https://github.com/ucsolarcarteam/epsilon-domovoi/blob/f730900e63cef55b8b166d6a3bff3de1dd8c8836/domovoi.py#L19)):_

> ``` Python
>     Check the path of each process, throw an error if the path is invalid
>     '''
>     def check_paths(self, solar_car_processes): 
> ```

Extra space

---

_[domovoi.py, line 52 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/epsilon-domovoi/15#-KUErI9P5sVs3mjB6Q_4:-KUErI9P5sVs3mjB6Q_5:b-32aynv) ([raw file](https://github.com/ucsolarcarteam/epsilon-domovoi/blob/f730900e63cef55b8b166d6a3bff3de1dd8c8836/domovoi.py#L52)):_

> ``` Python
>     Opens processes_file which should contain a list of paths to each SolarCarProcess, and makes an object for each one.
>     '''
>     def parse_file(self, processes_file): 
> ```

Looks like you added a thing here?

---

_[domovoi.py, line 64 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/epsilon-domovoi/15#-KUErUZYAvG2J-0uE2Qq:-KUErUZYAvG2J-0uE2Qr:b-zduvmu) ([raw file](https://github.com/ucsolarcarteam/epsilon-domovoi/blob/f730900e63cef55b8b166d6a3bff3de1dd8c8836/domovoi.py#L64)):_

> ``` Python
>             for solar_car_process in solar_car_processes:
>                 if solar_car_process.check_status():
>                     if solar_car_process.process.returncode == 0: # Default exit, removes the process from the list
> ```

Maybe "Good" exit instead of "Default"

---

_[domovoi.py, line 86 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/epsilon-domovoi/15#-KUErlW4n0mrqpuNXQDH:-KUErlW4n0mrqpuNXQDI:b-nuf40u) ([raw file](https://github.com/ucsolarcarteam/epsilon-domovoi/blob/f730900e63cef55b8b166d6a3bff3de1dd8c8836/domovoi.py#L86)):_

> ``` Python
>     parser.add_argument('processes_file', help='text file of solar car processes') # Adds in a positional argument for the process_file
>     args = parser.parse_args()# Stores the arguments the user inputted
>     os.makedirs("logs", exist_ok=True) # Makes a directory named logs.
> ```

Is this comment necessary?

---

_[solar_car_process.py, line 15 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/epsilon-domovoi/15#-KUErrb52vwT87x__BUC:-KUErrb52vwT87x__BUD:b6bcy41) ([raw file](https://github.com/ucsolarcarteam/epsilon-domovoi/blob/f730900e63cef55b8b166d6a3bff3de1dd8c8836/solar_car_process.py#L15)):_

> ``` Python
>     Attempt to start the process.
>     '''
>     def start(self): 
> ```

Extra space

---

_[solar_car_process.py, line 25 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/epsilon-domovoi/15#-KUErqagQO5DVWbaz8hD:-KUErqagQO5DVWbaz8hE:b6bcy41) ([raw file](https://github.com/ucsolarcarteam/epsilon-domovoi/blob/f730900e63cef55b8b166d6a3bff3de1dd8c8836/solar_car_process.py#L25)):_

> ``` Python
>         self.timesRestarted += 1
> 
>     def check_status(self): 
> ```

Extra space

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/epsilon-domovoi/15)_

**Comment by bill-luu** [comment]
Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

_[domovoi.py, line 19 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/epsilon-domovoi/15#-KUErLSdhqPtrl-z4soa:-KUFSv8bYLOHC9TETohU:b-886gsx) ([raw file](https://github.com/ucsolarcarteam/epsilon-domovoi/blob/f730900e63cef55b8b166d6a3bff3de1dd8c8836/domovoi.py#L19)):_
<details><summary>

<i>Previously, enochtsang (Enoch Tsang) wrote…</i></summary>



> Extra space
> </details>
> Fixed

---

_[domovoi.py, line 52 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/epsilon-domovoi/15#-KUErI9P5sVs3mjB6Q_4:-KUFSvxxFxQPro62epZN:b-886gsx) ([raw file](https://github.com/ucsolarcarteam/epsilon-domovoi/blob/f730900e63cef55b8b166d6a3bff3de1dd8c8836/domovoi.py#L52)):_
<details><summary>

<i>Previously, enochtsang (Enoch Tsang) wrote…</i></summary>



> Looks like you added a thing here?
> </details>
> Fixed

---

_[domovoi.py, line 64 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/epsilon-domovoi/15#-KUErUZYAvG2J-0uE2Qq:-KUFSwohltDkHEkqyVLz:b-886gsx) ([raw file](https://github.com/ucsolarcarteam/epsilon-domovoi/blob/f730900e63cef55b8b166d6a3bff3de1dd8c8836/domovoi.py#L64)):_
<details><summary>

<i>Previously, enochtsang (Enoch Tsang) wrote…</i></summary>



> Maybe "Good" exit instead of "Default"
> </details>
> Fixed

---

_[domovoi.py, line 86 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/epsilon-domovoi/15#-KUErlW4n0mrqpuNXQDH:-KUFSxWaAgUPKhXU0x8N:b-886gsx) ([raw file](https://github.com/ucsolarcarteam/epsilon-domovoi/blob/f730900e63cef55b8b166d6a3bff3de1dd8c8836/domovoi.py#L86)):_
<details><summary>

<i>Previously, enochtsang (Enoch Tsang) wrote…</i></summary>



> Is this comment necessary?
> </details>
> Fixed

---

_[solar_car_process.py, line 15 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/epsilon-domovoi/15#-KUErrb52vwT87x__BUC:-KUFSyZwEaj4MnZs-Ffn:b-886gsx) ([raw file](https://github.com/ucsolarcarteam/epsilon-domovoi/blob/f730900e63cef55b8b166d6a3bff3de1dd8c8836/solar_car_process.py#L15)):_
<details><summary>

<i>Previously, enochtsang (Enoch Tsang) wrote…</i></summary>



> Extra space
> </details>
> Fixed

---

_[solar_car_process.py, line 25 at r1](https://reviewable.io:443/reviews/ucsolarcarteam/epsilon-domovoi/15#-KUErqagQO5DVWbaz8hD:-KUFSz4dl_pnKEAjFXPM:b-886gsx) ([raw file](https://github.com/ucsolarcarteam/epsilon-domovoi/blob/f730900e63cef55b8b166d6a3bff3de1dd8c8836/solar_car_process.py#L25)):_
<details><summary>

<i>Previously, enochtsang (Enoch Tsang) wrote…</i></summary>



> Extra space
> </details>
> Fixed

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/epsilon-domovoi/15)_

**Comment by ExtraGravity** [comment]
Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/ucsolarcarteam/epsilon-domovoi/15)_

**Pull request merged**
